export const DEFAULT_MARKER = "[habit:: true]";
export const DEFAULT_PARENT_HEADING = "## 🌟 يومياتي";
export const DEFAULT_REFLECTION_HEADING = "### 📝 تدوينات اليوم";
export const DEFAULT_HABIT_NOTES_HEADING = "### 💬 ملاحظات العادات";
export const REFLECTION_ENTRY_TYPES = ["Good", "Bad", "Lesson", "Idea"];

export function normalizeReflectionType(type) {
  const cleanType = String(type || "").trim();
  return REFLECTION_ENTRY_TYPES.includes(cleanType) ? cleanType : "Idea";
}

export const DEBOUNCE_DELAY_MS = 300;

export const DAY_KEYS = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];

export const VIEW_TYPE_WEEKLY = "weekly-habits-view";

export const HABIT_COLORS_PALETTE = [
  { id: "rose", hex: "#f43f5e" },
  { id: "pink", hex: "#ec4899" },
  { id: "orange", hex: "#f97316" },
  { id: "amber", hex: "#f59e0b" },
  { id: "lime", hex: "#84cc16" },
  { id: "green", hex: "#10b981" },
  { id: "teal", hex: "#14b8a6" },
  { id: "cyan", hex: "#06b6d4" },
  { id: "blue", hex: "#3b82f6" },
  { id: "indigo", hex: "#6366f1" },
  { id: "purple", hex: "#8b5cf6" },
  { id: "slate", hex: "#64748b" },
];

export function resolveHabitColorHex(colorId) {
  const entry = HABIT_COLORS_PALETTE.find(c => c.id === colorId);
  return entry ? entry.hex : HABIT_COLORS_PALETTE[0].hex;
}

export const DEFAULT_SETTINGS = {
  marker: DEFAULT_MARKER,
  showCount: true,
  debugMode: false,
  hideYear: false,
  lastSeenVersion: "",
  lifetimeCompleted: null,
  deletedHabits: [],

  habits: [],

  weekStartDay: 6,
  showHijriDate: true,

  habitNotesFolder: "Core Habits",
  nativeMigrated: false,

  dailyParentHeading: DEFAULT_PARENT_HEADING,
  habitHeading: "### 🔄 تتبع العادات",
  autoWriteHabits: true,

  dailyNotesFolder: "",
  dailyNotesSource: "auto",
  dateFormat: "YYYY-MM-DD",

  language: "ar",



  enableOpenReminder: true,

  enableSound: true,

  collapsedGroups: [],
  collapsedGroupsSemanticMigrated: false,

  enableHabitContext: true,
  habitLogHeading: DEFAULT_HABIT_NOTES_HEADING,

  enableReflectionJournal: true,
  reflectionHeading: DEFAULT_REFLECTION_HEADING,
  streakBreakOnMissing: false,
  diaryViewMode: "grouped",
};

export const TRANSLATIONS = {
  en: {
    direction: "ltr",
    settings_title: "Core Habits",
    habit_marker: "Habit marker",
    habit_marker_desc: "String to identify habits in daily notes.",
    show_count: "Show progress",
    show_count_desc: "Show completed/total count in header.",
    hide_year: "Hide year",
    week_start: "Week start day",
    week_start_desc: "Day the week starts on.",
    add_habit_btn: "+ Add habit",
    edit_habit_title: "Edit Habit",
    add_habit_title: "Add New Habit",
    delete: "Delete",
    cancel: "Cancel",
    error_name_required: "Habit name is required",
    success_added: 'Added "{habit}"',
    language: "Language",
    language_desc: "Choose plugin interface language.",
    sat: "Saturday",
    sun: "Sunday",
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    habit_name: "Habit name",
    frequency: "Frequency",
    import_habits: "Import from today's note",
    import_desc: "Scan today's note for habits and add them.",
    edit_habit: "Edit",
    streak_break_on_missing: "Missing note breaks streak",
    streak_break_on_missing_desc: "If enabled, a day with no daily note counts as a missed day and breaks your streak. If disabled (default), missing notes are ignored — streak is only broken when a note exists but the habit is unchecked.",
    habit_section_heading: "Habit section heading",
    habit_section_heading_desc: "The heading under which habits will be written in daily notes.",
    auto_write_habits: "Auto-write habits",
    auto_write_habits_desc: "Automatically add habits to daily notes when you open them.",
    level: "Level",
    build_habit: "Build 🟢",
    break_habit: "Break 🔴",
    consistency_excellent: "Excellent",
    consistency_good: "Good",
    consistency_fair: "Fair",
    consistency_low: "Needs work",
    open_reminder: "Reminder on open",
    open_reminder_desc: "Show a notice with incomplete habits count when Obsidian opens.",
    open_reminder_notice: "incomplete habits today",
    enable_sound: "Enable sound effects",
    enable_sound_desc: "Play feedback sounds when checking/unchecking habits and reaching milestones.",
    show_hijri_date: "Show Hijri date",
    show_hijri_date_desc: "Display the Hijri (Islamic) calendar date alongside the Gregorian date.",
    parent_habit: "Parent habit (optional)",
    parent_habit_none: "— None (top-level) —",
    tab_basics: "⚙️ Basics",
    tab_habits: "📋 Habits",
    tab_advanced: "🔗 Advanced",
    tab_guide: "📖 Guide",
    empty_state_title: "No habits yet",
    empty_state_desc: "Start your journey towards better habits and stick to them daily.",
    empty_state_btn: "+ Add first habit",
    enable_habit_context: "Enable habit context",
    enable_habit_context_desc: "Allow adding timestamped habit comments inside the matching Daily Note.",
    habit_log_heading: "Habit log heading",
    habit_log_heading_desc: "The heading inside each Daily Note where comments will be injected.",
    enable_reflection_journal: "Enable daily journal",
    enable_reflection_journal_desc: "Allow writing daily logs into the matching Daily Note.",
    reflection_heading: "Daily logs heading",
    reflection_heading_desc: "The heading inside each Daily Note where daily entries will be listed.",
    reflection_modal_title: "How was your day?",
    reflection_good: "Good",
    reflection_bad: "Bad",
    reflection_lesson: "Lesson",
    reflection_idea: "Idea",

    // Milestone 1 - Localization keys
    date_format_short: "MMM D",
    date_format_medium: "D MMM",
    date_format_long: "ddd, D MMM",
    loading_habits: "Loading habits...",
    weekly_view_error: "⚠️ Weekly view error",
    tab_weekly_grid: "Weekly Grid",
    tab_statistics: "Statistics",
    tab_my_diary: "My Diary",
    back_to_today: "Back to Today",
    today: "Today",
    gregorian_abbr: "G",
    hijri_abbr: "H",
    refresh: "Refresh",
    refresh_title: "Refresh data",
    refreshed_success: "✓ Refreshed",
    streak_title: "Streak: {streak} consecutive day(s)",
    grid_previous_day_tooltip: "Previous day",
    grid_next_day_tooltip: "Next day",

    // Onboarding
    onboarding_title_1: "🎉 Welcome to Core Habits 3.2",
    onboarding_title_2: "🧠 Habit Engineering",
    onboarding_title_3: "⚡ The New Data Engine",
    onboarding_back: "Back",
    onboarding_next: "Next",
    onboarding_start: "Start Now 🚀",
    onboarding_desc_1: "We have completely rebuilt the plugin to be faster, more beautiful, and smarter. This is not just a habit tracker; it's a tool to build your 'Core Identity'.",
    onboarding_feat_1: "Completely modernized UI",
    onboarding_feat_2: "Powerful pattern & recovery analytics",
    onboarding_feat_3: "Absolute data safety (never lost)",
    onboarding_desc_2: "Habits are not built with pressure, but with smart engineering. In the new version, you can engineer every habit:",
    onboarding_feat_4: "Define Identity (Who do I want to be?)",
    onboarding_feat_5: "Link to a Cue (Time/Location)",
    onboarding_feat_6: "Reduce Friction (Make it easy)",
    onboarding_feat_7: "Set an immediate Reward",
    onboarding_desc_3: "Data is now decentralized! Your completions (checkmarks) are saved directly in your daily notes. Even if you delete a habit, your historical achievements are saved forever.",
    onboarding_tip_3: "💡 Tip: Write your thoughts about the habit, and the 'Reflection Log' will collect them automatically.",

    // Guide Panel
    guide_start_title: "Getting Started",
    guide_start_step1: "Go to the 'Habits' tab and add your habits.",
    guide_start_step2: "Open 'Weekly Grid' from the calendar icon in the sidebar.",
    guide_start_step3: "Click a cell to mark it ✓, skip ⊘, or unmark ☐.",
    guide_start_step4: "Track your stats from the 'Statistics' tab.",
    guide_symbols_title: "Symbols Meaning",
    guide_symbols_completed: "Successfully completed",
    guide_symbols_missed: "Missed (Past day)",
    guide_symbols_skipped: "Skipped (Streak preserved)",
    guide_symbols_pending: "Pending today",
    guide_symbols_not_scheduled: "Not scheduled for this day",
    guide_folders_title: "Files and Folders",
    guide_folders_step1: "Each habit has a file saved in 'Core Habits/Active'.",
    guide_folders_step2: "The file contains the habit properties (Frontmatter), notes, and a daily log.",
    guide_folders_step3: "When archiving a habit, its file automatically moves to the 'Archive' folder.",
    guide_levels_title: "Gradation & Levels",
    guide_levels_desc: "The plugin allows breaking down a big habit into 5 levels (e.g., read a page -> read a chapter). You can't move to the next level without meeting the current level's condition.",
    guide_parent_title: "Parent & Child Habits",
    guide_parent_desc: "You can link small habits (children) to a main habit (parent). In the tracker, child habits appear under the parent, and you can collapse the list to focus.",
    guide_comments_title: "Voice & Text Comments",
    guide_comments_desc: "You can add a daily text or voice comment for each habit by right-clicking a day cell and selecting 'Add Comment'. It will be saved in your daily note.",
    guide_footer_tip: "Tip: 'Consistency over Intensity'. Start today with the tiniest action!",

    // Popups
    reflection_notes_placeholder: "How was your day? Quick notes...",
    reflection_record_hold: "🎙️ Record (Hold)",
    reflection_record_title: "Press and hold to record a voice note",
    reflection_save: "💾 Save reflection",
    reflection_mic_stop: "⏹ Stop",
    reflection_mic_recording: "Recording... {time}",
    reflection_mic_failed: "Microphone access failed!",
    reflection_mic_processing: "Processing audio...",
    reflection_mic_btn_voice: "🎙️ Voice Note",
    reflection_mic_save_failed: "Failed to save audio file!",
    reflection_mic_stop_first: "Stop recording first!",
    reflection_saving: "Saving...",
    reflection_save_success: "✅ Saved reflection to daily note: {file}",
    reflection_save_success_comment: "✅ Saved comment to: {file}",

    comment_placeholder: "What happened? Why delayed? Feeling?",
    comment_loading: "Loading previous comment...",
    comment_save: "💾 Save",

    rename_updating: "Updating files...",

    // Settings additional
    settings_habits_folder: "Habit notes folder",
    settings_habits_folder_desc: "Folder where habit notes (Active/Archive) will be saved",
    settings_move_folder_confirm: "Do you want to move the habit folder from \"{oldRoot}\" to \"{newRoot}\"?",
    settings_folder_moved_success: "✅ Folder moved",
    settings_folder_move_error: "Error moving folder",
    settings_hide_year_desc: "Hide the year in the header",
    settings_import_today: "📝 Today's Note",
    settings_no_today_note: "No daily note found for today.",
    settings_imported_count: "✅ Imported {count} new habits!",
    settings_no_new_habits: "No new habits found.",
    settings_import_failed: "Import failed: {message}",
    settings_choose_file: "📂 Choose File",
    settings_imported_from_file: "✅ Imported {count} habits from \"{name}\"",
    settings_search_habits: "🔍 Search habits...",
    settings_archived_habits: "📦 Archived Habits",
    settings_danger_zone: "Danger Zone",
    settings_delete_all: "Delete all habits",
    settings_delete_all_desc: "Permanently delete all active habits (archived will be kept). This cannot be undone.",
    settings_delete_all_btn: "🗑️ Delete all",
    settings_delete_all_confirm: "⚠️ Delete {count} active habits?",
    settings_all_deleted_success: "✅ All active habits deleted",
    settings_formatting_heading: "📐 Formatting & Structure",
    settings_daily_parent_heading: "Daily note parent heading",
    settings_daily_parent_heading_desc: "The parent heading under which habits and comments sections will be placed in daily notes.",
    settings_other_heading: "⚙️ Other Settings",
    settings_advanced_notes_toggle: "Advanced Daily Notes Settings",
    settings_daily_integration: "Daily notes integration",
    settings_daily_folder_label: "📁 Folder: {folder}",
    settings_daily_format_label: "📄 Format: {format}",
    settings_daily_template_label: "📝 Template: {template}",
    settings_source_label: "Settings source",
    settings_source_desc: "Auto = detect from Daily Notes / Periodic Notes. Manual = use the fields below.",
    settings_source_auto: "Auto",
    settings_daily_folder: "Daily notes folder",
    settings_daily_folder_desc: "Relative path to folder (leave empty for vault root)",

    // GridRenderer strings
    grid_expand_children: "Expand children",
    grid_collapse_children: "Collapse children",
    grid_diary_label: " Diary",
    grid_diary_exists_tooltip: "Diary entry exists",
    grid_diary_add_tooltip: "Add daily reflection",
    grid_hint_tip: "💡 Tip: Long-press or right-click any checkbox to record a voice note for that habit.",
    grid_hint_hide: "Hide hint",
    grid_no_note_tooltip: "📝 No note for this day",
    grid_click_open_note_tooltip: "Click to open note",
    grid_type_break: "Break habit",
    grid_type_build: "Build habit",
    grid_collapse_expand_tooltip: "Collapse / expand children",
    grid_open_habit_page_tooltip: "Open habit page",
    grid_no_linked_page_notice: "⚠️ No linked page found",
    grid_cell_right_click_hint: "Right-click to add comment",
    grid_habit_archived_tooltip: "🔒 Habit Archived\n{title}",
    grid_create_note_confirm: "No note for this day. Create one?",
    grid_btn_create: "Create",
    grid_create_note_error: "⚠️ Could not create note",
    grid_no_note_error: "⚠️ No note for this day",
    grid_habit_not_found_error: "⚠️ Habit not found in note",
    grid_update_habit_error: "⚠️ Error updating habit",
    grid_completion_rate: "Completion Rate",
    grid_completion_gap: "🚀 Good start! {gap}% left to match last week's record ({lastRate}%).",
    grid_completion_match: "🔥 Awesome! You matched last week's record ({lastRate}%). One step to break the barrier!",
    grid_completion_break: "🏆 Barrier broken! You are leading by (+{lead}%) over last week.",
    completion_msg_1: "🌟 All habits done!",
    completion_msg_2: "💪 Perfect day!",
    completion_msg_3: "🎯 Excellent! Keep going",
    habit_log_disabled: "Habit context feature is disabled in settings.",
    save_habit_first_for_comments: "Save the habit first to add and read comments.",
    tab_basics_num: "1. Basics",
    tab_gradation_num: "2. Gradation",
    tab_log_num: "3. Log",
    habit_name_placeholder: "e.g. Fajr prayer at mosque",
    rename_old_notes_label: "Rename in all older notes? (Optional)",
    rename_old_notes_hint: "💡 This will replace the current name and all previous aliases with the new name across your vault.",
    no_linked_file: "📁 No linked file (will be created)",
    child_habits_label: "Child Habits:",
    color: "Color",
    schedule_days: "Frequency",
    sun_short: "Su", mon_short: "M", tue_short: "Tu", wed_short: "W", thu_short: "Th", fri_short: "F", sat_short: "Sa",
    habit_engineering_summary: "💡 Habit Engineering (Optional): Deep analysis questions",
    habit_type_build: "Build",
    habit_type_break: "Break",
    notes_label: "Notes (optional)",
    notes_hint: "Free space: time, place, reminders, anything you want",
    notes_placeholder: "e.g. This habit is at 6am after coffee...",
    identity_label: "Target Identity",
    identity_hint_build: "Instead of 'I want to read', say 'I am a reader'",
    identity_hint_break: "Who do you want to become?",
    identity_placeholder_build: "e.g. I am a consistent reader",
    identity_placeholder_break: "e.g. I am a non-smoker",
    cue_label_build: "Cue (When & Where?)",
    cue_label_break: "Cue (Hide)",
    cue_hint_build: "I will do [habit] at [time] in [place]",
    cue_hint_break: "What triggers it? Remove or hide it",
    cue_placeholder_build: "e.g. Right after Fajr in study room",
    cue_placeholder_break: "e.g. Delete distracting app",
    friction_label_build: "Make it Easy",
    friction_label_break: "Make it Difficult",
    friction_hint_build: "Start with under 2 minutes",
    friction_hint_break: "Add steps/obstacles to prevent starting",
    friction_placeholder_build: "e.g. Prepare gym clothes the night before",
    friction_placeholder_break: "e.g. Keep phone away from bedroom",
    reward_label_build: "Reward (Immediate)",
    reward_label_break: "Punishment (Immediate)",
    reward_hint_build: "Reward yourself immediately",
    reward_hint_break: "Immediate consequence if you fail?",
    reward_placeholder_build: "e.g. Favorite cup of coffee",
    reward_placeholder_break: "e.g. Donate 50 SAR as penalty",
    gradation_hint: "Graduate in your work until you reach your goal",
    gradation_explanation: "💡 Gradation Method: Big habits start with tiny steps. Focus only on the current level until you meet the 'Condition'.",
    target_habit_level_label: "Target Habit Level",
    condition_label: "Condition",
    cond_select: "Select condition...",
    cond_7d: "7 continuous days",
    cond_14d: "14 continuous days",
    cond_21d: "21 continuous days",
    cond_30d: "30 continuous days",
    cond_lifestyle: "No condition (Lifestyle)",
    placeholder_lvl_1: "Atomic start: 1 verse, or 1 push-up",
    placeholder_lvl_2: "Real start: 1 page, or 5 min exercise",
    placeholder_lvl_3: "Moderate growth: 2 pages, or 15 min exercise",
    placeholder_lvl_4: "Challenge level: half juz, or 30 min exercise",
    placeholder_lvl_5: "Ultimate goal: 1 full juz, or 45 min workout",
    error_fill_level: "Fill goal and condition first",
    save_btn: "💾 Save",
    color_rose: "Rose", color_pink: "Pink", color_orange: "Orange", color_amber: "Amber", color_lime: "Lime", color_green: "Green", color_teal: "Teal", color_cyan: "Cyan", color_blue: "Blue", color_indigo: "Indigo", color_purple: "Purple", color_slate: "Slate",
    yes_sure: "Yes, sure",
    settings_source_daily: "Connected to Daily Notes (auto)",
    settings_source_periodic: "Connected to Periodic Notes (auto)",
    settings_source_manual: "Manual configuration",
    settings_source_defaults: "Default values (YYYY-MM-DD)",
    settings_source_manual_opt: "Manual",
    settings_daily_format: "Date format",
    settings_daily_format_desc: "Moment.js format for filename",
    settings_habit_context_heading: "💬 Habit Context (Comments)",
    settings_journal_heading: "📝 Daily Journal",
    settings_collapse_expand_tooltip: "Collapse / expand children",
    schedule_daily: "🔁 Daily",
    schedule_days_count: "🗓️ {count} Days",
    action_move_up: "Move Up",
    action_moved_up_success: "✅ Moved up",
    action_move_down: "Move Down",
    action_moved_down_success: "✅ Moved down",
    action_delete_confirm: "⚠️ Delete \"{name}\"?",
    action_archive: "Archive",
    action_archived_success: "✅ Archived",
    settings_expand_children: "Expand children",
    settings_collapse_children: "Collapse children",
    settings_no_archived_habits: "No archived habits",
    settings_archive_date: "Archive Date",
    settings_longest_streak: "Longest Streak",
    action_restore: "Restore",
    action_restored_success: "✅ Restored",
    action_delete_permanently: "Delete Permanently",
    action_delete_permanently_confirm: "⚠️ Permanently delete \"{name}\"?",
    action_deleted_permanently_success: "✅ Permanently deleted",
    notice_deleted_habit: "🗑️ Deleted \"{name}\"",
    action_undo: "Undo",
    action_restored_habit_success: "✅ Habit restored",

    // StreakStatsComponent
    stats_days_one: "day",
    stats_days_other: "days",
    stats_none: "None",
    stats_calculating: "Calculating...",
    stats_longest_label: "Longest:",
    stats_current_label: "Current:",
    stats_first_completion: "First completion",
    stats_days_ago: "({count} {unit})",
    stats_consistency: "Consistency",
    stats_last_30_days: "(30 days)",
    stats_recovery_speed: "Recovery Speed",
    stats_recovery_tooltip: "Lower number means faster recovery after missing a habit",
    stats_recovery_avg: "Returns in {days} days on avg",
    stats_recovery_behind: "Behind average ({days}d). Simplify & recover!",
    stats_recovery_resilience: "High resilience champ!",
    stats_recovery_good: "Good recovery speed",
    stats_recovery_simplify: "Decision: Simplify post-fail",
    stats_leak_alert: "Leak Alert",
    stats_leak_days: "{count} days",
    stats_leak_simplify: "(Simplify habit to stop the leak!)",
    stats_error_loading: "Error loading stats",

    // LogViewer
    log_header_title: "Habit Context Log",
    log_add_note_btn: "🎙️ Add Note Today",
    log_loading: "Loading log...",
    log_empty_state: "Log is empty. Keep tracking and document your progress day by day!",
    log_error: "Error loading log",
    date_format_log_day: "DD MMM",

    // DiaryRenderer
    diary_weekly_title: "Weekly diary",
    diary_add_today_btn: "Today entry",
    diary_mode_grouped: "Grouped",
    diary_mode_timeline: "Timeline",
    diary_mode_by_type: "By type",
    diary_empty_title: "No entries this week",
    diary_empty_desc: "Use the button above. Entries are saved inside the matching Daily Note.",
    diary_count_one: "1 entry",
    diary_count_other: "{count} entries",
    diary_add_entry_tooltip: "Add entry for this day",
    date_format_diary_header: "dddd, D MMMM",

    // DashboardRenderer
    stats_calculating_lifetime: "Calculating...",
    stats_calculating_lifetime_progress: "Calculating... ({progress}/{total} files) ⏳",
    stats_lifetime_achievements: "Lifetime Achievements",
    stats_lifetime_subtitle: "🌟 Total [x] in your vault",
    stats_calculate_btn: "Calculate",
    stats_identity_mix: "Identity Mix",
    stats_identity_build: "Build: {count}",
    stats_identity_break: "Break: {count}",
    stats_advisory_tip: "Tip: If you make a new decision based on these trends, write it immediately in today's note or the habit file.",
    stats_weekly_trends_title: "📈 Recent Weekly Trends",
    stats_weekly_trends_desc: "A look at your last 4 weeks only to discover your current trajectory and make quick course corrections.",
    stats_table_header_week: "Week",
    stats_table_header_rate: "Completion Rate",
    stats_table_header_trend: "Trend",
    stats_week_current: "Current Week (Selected)",
    stats_week_last: "Last Week (-1)",
    stats_week_index: "Week -{index}",
    stats_trend_up: "🟢 +{diff}%",
    stats_trend_down: "🔴 -{diff}%",
    stats_trend_stable: "➖ 0%",
    stats_focus_best_label: "Most Consistent",
    stats_focus_worst_label: "Needs Attention",
    stats_daily_patterns_title: "📅 Day-by-Day Patterns (Average)",
    stats_daily_patterns_desc: "Average performance over the last 28 days. Find your 'leaky' day to fix and your golden day to leverage.",
    stats_daily_patterns_guideline: "Guideline: Red indicates your weakest day that needs a routine fix, and Green is your strongest. Double down on what works!",
    success_updated: "✅ Updated {name}",
    error_habit_file_not_found: "⚠️ Habit file not found.",
    comma_separator: ", ",
    error_file_exists: "A file already exists at the target path: \"{path}\"",
    error_duplicate_habit_name: "A habit (active or archived) with this name already exists: \"{name}\"",
    rename_confirm_title: "⚠️ Update all files",
    rename_confirm_desc: "Will change \"{oldName}\" to \"{newName}\" in {count} file(s).",
    rename_confirm_btn_all: "Yes, update all",
    rename_cancelled_notice: "⚠️ Cancelled. Updated: {count}",
    rename_success_notice: "✅ Successfully cleaned {count} historical links",
    rename_error_notice: "❌ Error during update",
    rename_no_files_notice: "No old files found to update",
    habit_notes_free_space_marker: "> **Free Space for Notes:**",
    habit_notes_placeholder: "> (Write your deep motivations or thoughts about this habit here...)",
    habit_template_engineering_title: "> [!info] 🧠 Habit Engineering",
    habit_template_identity_prefix: "> **Desired Identity:**",
    habit_template_cue_prefix: "> **Cue (Time/Location):**",
    habit_template_friction_prefix: "> **Reduce Friction:**",
    habit_template_reward_prefix: "> **Reward:**",
    habit_template_append_marker_comment: "<!-- Voice memos and text logs are appended here automatically by the plugin -->",
    error_modifying_note: "⚠️ Error modifying note.",
  },
  ar: {
    direction: "rtl",
    reflection_good: "جيد",
    reflection_bad: "سيء",
    reflection_lesson: "درس",
    reflection_idea: "فكرة",
    settings_title: "إعدادات Core Habits",
    habit_marker: "علامة العادة",
    habit_marker_desc: "النص المستخدم لتمييز العادات في الملاحظات اليومية.",
    show_count: "إظهار التقدم",
    show_count_desc: "عرض عدد المكتمل/الكلي في العنوان.",
    hide_year: "إخفاء السنة",
    week_start: "بداية الأسبوع",
    week_start_desc: "اليوم الذي يبدأ به الأسبوع.",
    add_habit_btn: "+ إضافة عادة",
    edit_habit_title: "تعديل العادة",
    add_habit_title: "إضافة عادة جديدة",
    delete: "حذف",
    cancel: "إلغاء",
    error_name_required: "اسم العادة مطلوب",
    success_added: 'تمت إضافة "{habit}"',
    language: "اللغة / Language",
    language_desc: "اختر لغة الواجهة.",
    sat: "السبت",
    sun: "الأحد",
    mon: "الاثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    habit_name: "اسم العادة",
    frequency: "التكرار",
    import_habits: "استيراد من ملاحظة اليوم",
    import_desc: "فحص ملاحظة اليوم وإضافة العادات الجديدة للإعدادات.",
    edit_habit: "تعديل",
    streak_break_on_missing: "غياب الملاحظة يكسر السلسلة",
    streak_break_on_missing_desc: "عند التفعيل: يوم بلا ملاحظة يومية = يوم فائت يكسر السلسلة. عند الإيقاف (الافتراضي): الأيام بلا ملاحظة تُتجاهل — السلسلة تنكسر فقط عندما توجد ملاحظة لكن العادة لم تُنجَز.",
    level: "المستوى",
    habit_section_heading: "عنوان قسم العادات",
    habit_section_heading_desc: "العنوان الذي سيتم كتابة العادات تحته في الملاحظات اليومية.",
    auto_write_habits: "كتابة العادات تلقائياً",
    auto_write_habits_desc: "إضافة العادات تلقائياً عند فتح الملاحظة اليومية.",
    build_habit: "بناء 🟢",
    break_habit: "كسر 🔴",
    consistency_excellent: "ممتاز",
    consistency_good: "جيد",
    consistency_fair: "مقبول",
    consistency_low: "يحتاج تحسين",
    open_reminder: "تذكير عند الفتح",
    open_reminder_desc: "عرض إشعار بعدد العادات غير المكتملة عند فتح Obsidian.",
    open_reminder_notice: "عادة غير مكتملة اليوم",
    enable_sound: "تفعيل المؤثرات الصوتية",
    enable_sound_desc: "تشغيل أصوات عند تحديد العادات وإلغائها والوصول إلى الإنجازات.",
    show_hijri_date: "إظهار التاريخ الهجري",
    show_hijri_date_desc: "عرض التاريخ الهجري بجانب التاريخ الميلادي.",
    parent_habit: "العادة الأم (اختياري)",
    parent_habit_none: "— بلا (مستقلة) —",
    tab_basics: "⚙️ الأساسيات",
    tab_habits: "📋 العادات",
    tab_advanced: "🔗 متقدم",
    tab_guide: "📖 دليل الإضافة",
    empty_state_title: "لا توجد عادات بعد",
    empty_state_desc: "ابدأ رحلتك نحو عادات أفضل والتزم بها يومياً.",
    empty_state_btn: "+ إضافة أول عادة",
    enable_habit_context: "تفعيل تعليقات العادة (سياق العادة)",
    enable_habit_context_desc: "السماح بكتابة تعليقات العادات داخل ملف اليوم نفسه.",
    habit_log_heading: "عنوان تعليقات العادات",
    habit_log_heading_desc: "العنوان داخل ملف اليوم الذي ستُحفظ تحته تعليقات العادات.",
    enable_reflection_journal: "تفعيل سجل اليوميات",
    enable_reflection_journal_desc: "السماح بكتابة اليوميات داخل ملف اليوم نفسه بدل ملف مركزي.",
    reflection_heading: "عنوان قسم اليوميات",
    reflection_heading_desc: "العنوان داخل ملف اليوم الذي ستُضاف تحته تدوينات اليوم.",
    reflection_modal_title: "كيف كان يومك تقييماً عاماً؟",

    // Milestone 1 - Localization keys
    date_format_short: "D MMMM",
    date_format_medium: "D MMMM",
    date_format_long: "dddd، D MMMM",
    loading_habits: "جاري تحميل العادات...",
    weekly_view_error: "⚠️ خطأ في عرض الأسبوع",
    tab_weekly_grid: "الجدول الأسبوعي",
    tab_statistics: "الإحصائيات",
    tab_my_diary: "يومياتي",
    back_to_today: "العودة لليوم الحالي",
    today: "اليوم",
    gregorian_abbr: "م",
    hijri_abbr: "هـ",
    refresh: "تحديث",
    refresh_title: "تحديث البيانات",
    refreshed_success: "✓ تم التحديث",
    streak_title: "سلسلة الاستمرار: {streak} يوم متواصل",
    grid_previous_day_tooltip: "اليوم السابق",
    grid_next_day_tooltip: "اليوم التالي",

    // Onboarding
    onboarding_title_1: "🎉 مرحباً بك في Core Habits 3.2",
    onboarding_title_2: "🧠 هندسة العادات (Habit Engineering)",
    onboarding_title_3: "⚡ محرك البيانات الجديد",
    onboarding_back: "السابق",
    onboarding_next: "التالي",
    onboarding_start: "ابدأ الآن 🚀",
    onboarding_desc_1: "لقد قمنا بإعادة بناء الإضافة بالكامل لتكون أسرع، أجمل، وأكثر ذكاءً. هذه ليست مجرد إضافة لتتبع العادات، إنها أداة لبناء 'هويتك الأساسية'.",
    onboarding_feat_1: "واجهة عصرية بالكامل",
    onboarding_feat_2: "تحليل قوي للأنماط والتعافي",
    onboarding_feat_3: "أمان تام للبيانات (لا تضيع أبداً)",
    onboarding_desc_2: "العادة لا تُبنى بالضغط، بل بالهندسة الذكية. في الإصدار الجديد، يمكنك هندسة كل عادة بدقة:",
    onboarding_feat_4: "حدد هويتك (من أريد أن أكون؟)",
    onboarding_feat_5: "اربطها بمحفز (زمان/مكان)",
    onboarding_feat_6: "قلل الاحتكاك (اجعلها سهلة)",
    onboarding_feat_7: "حدد مكافأتك الفورية",
    onboarding_desc_3: "البيانات الآن لا مركزية! إنجازاتك (علامات الصح) تحفظ بداخل اليوميات نفسها. حتى لو قمت بحذف العادة من الإعدادات، إنجازاتك التاريخية ستظل محفورة في يومياتك للأبد في 'إجمالي الإنجازات'.",
    onboarding_tip_3: "💡 نصيحة: اكتب أفكارك ويومياتك عن العادة وسيقوم 'سجل التدوينات' بجمعها لك تلقائياً.",

    // Guide Panel
    guide_start_title: "كيف تبدأ",
    guide_start_step1: "اذهب إلى تبويب 'العادات' وأضف عاداتك.",
    guide_start_step2: "افتح 'الجدول الأسبوعي' من أيقونة التقويم في الشريط الجانبي.",
    guide_start_step3: "اضغط على الخلية لتعليم العادة ✓ أو تخطيها ⊘ أو إلغاء تحديدها ☐.",
    guide_start_step4: "تابع إحصائياتك من تبويب 'الإحصائيات'.",
    guide_symbols_title: "معاني الرموز",
    guide_symbols_completed: "مكتمل بنجاح",
    guide_symbols_missed: "فائت (يوم مضى)",
    guide_symbols_skipped: "تم التخطي (السلسلة لا تنكسر)",
    guide_symbols_pending: "بانتظار الإنجاز",
    guide_symbols_not_scheduled: "غير مجدول لهذا اليوم",
    guide_folders_title: "نظام الملفات والمجلدات",
    guide_folders_step1: "يتم حفظ ملف لكل عادة داخل مجلد 'Core Habits/Active'.",
    guide_folders_step2: "يحتوي الملف على خصائص العادة (Frontmatter) وملاحظات وسجل يومي.",
    guide_folders_step3: "عند أرشفة العادة، ينتقل ملفها تلقائياً إلى مجلد 'Archive'.",
    guide_levels_title: "التدرج والمراحل",
    guide_levels_desc: "تتيح لك الإضافة تقسيم العادة الكبيرة إلى 5 مستويات (مثلاً: قراءة صفحة -> قراءة فصل -> كتاب). لا يمكنك الانتقال للمستوى التالي إلا بعد إنجاز شرط المستوى الحالي.",
    guide_parent_title: "العادات المرتبطة (أب وأبناء)",
    guide_parent_desc: "يمكنك ربط عادات صغيرة (أبناء) بعادة رئيسية (أب). في واجهة التتبع، ستظهر العادات الأبناء أسفل العادة الأب، ويمكنك طي القائمة للتركيز.",
    guide_comments_title: "التعليقات الصوتية والنصية",
    guide_comments_desc: "يمكنك إضافة تعليق نصي أو تسجيل صوتي يومي لكل عادة عن طريق النقر بزر الماوس الأيمن على خلية اليوم واختيار 'إضافة تعليق'. سيتم حفظه في ملف اليومية.",
    guide_footer_tip: "نصيحة: 'القليل المستمر خير من الكثير المنقطع'. ابدأ اليوم بأصغر فعل ممكن!",

    // Popups
    reflection_notes_placeholder: "كيف كان يومك؟ ملاحظات سريعة...",
    reflection_record_hold: "🎙️ تسجيل (اضغط مطولاً)",
    reflection_record_title: "اضغط مطولاً لتسجيل ملاحظة صوتية",
    reflection_save: "💾 حفظ التدوين",
    reflection_mic_stop: "⏹ إيقاف",
    reflection_mic_recording: "جاري التسجيل... {time}",
    reflection_mic_failed: "فشل الوصول للميكروفون!",
    reflection_mic_processing: "معالجة الصوت...",
    reflection_mic_btn_voice: "🎙️ تسجيل صوتي",
    reflection_mic_save_failed: "فشل حفظ الملف الصوتي!",
    reflection_mic_stop_first: "أوقف التسجيل أولاً!",
    reflection_saving: "جاري...",
    reflection_save_success: "✅ تم حفظ التدوين في ملف اليوم: {file}",
    reflection_save_success_comment: "✅ تم حفظ التعليق في: {file}",

    comment_placeholder: "ماذا حدث؟ لماذا تأخرت؟ ما شعورك؟",
    comment_loading: "جاري تحميل التعليق السابق...",
    comment_save: "💾 حفظ",

    rename_updating: "جارٍ تحديث الملفات...",

    // Settings additional
    settings_habits_folder: "مجلد ملفات العادات",
    settings_habits_folder_desc: "المجلد الذي ستحفظ فيه ملفات العادات (النشطة والمؤرشفة)",
    settings_move_folder_confirm: "هل تريد نقل مجلد العادات من \"{oldRoot}\" إلى \"{newRoot}\"؟",
    settings_folder_moved_success: "✅ تم نقل المجلد",
    settings_folder_move_error: "حدث خطأ أثناء نقل المجلد",
    settings_hide_year_desc: "إخفاء السنة في العنوان",
    settings_import_today: "📝 ملاحظة اليوم",
    settings_no_today_note: "لا توجد ملاحظة لليوم",
    settings_imported_count: "✅ تم استيراد {count} عادة جديدة!",
    settings_no_new_habits: "لم يتم العثور على عادات جديدة",
    settings_import_failed: "فشل الاستيراد: {message}",
    settings_choose_file: "📂 اختيار ملف",
    settings_imported_from_file: "✅ تم استيراد {count} عادة من \"{name}\"",
    settings_search_habits: "🔍 بحث في العادات...",
    settings_archived_habits: "📦 العادات المؤرشفة",
    settings_danger_zone: "منطقة الخطر",
    settings_delete_all: "حذف جميع العادات",
    settings_delete_all_desc: "حذف جميع العادات النشطة نهائياً (لن يتم حذف المؤرشفة). هذا الإجراء لا يمكن التراجع عنه.",
    settings_delete_all_btn: "🗑️ حذف الكل",
    settings_delete_all_confirm: "⚠️ هل تريد حذف {count} عادة نشطة؟",
    settings_all_deleted_success: "✅ تم حذف جميع العادات النشطة",
    settings_formatting_heading: "📐 إعدادات البنية والتنسيق (Formatting & Structure)",
    settings_daily_parent_heading: "عنوان القسم الرئيسي اليومي",
    settings_daily_parent_heading_desc: "العنوان الرئيسي الذي سيتم كتابة أقسام العادات والتعليقات تحته في ملف اليومية.",
    settings_other_heading: "⚙️ إعدادات أخرى",
    settings_advanced_notes_toggle: "إعدادات متقدمة للملاحظات اليومية (Daily Notes)",
    settings_daily_integration: "التكامل مع الملاحظات اليومية",
    settings_daily_folder_label: "📁 المجلد: {folder}",
    settings_daily_format_label: "📄 الصيغة: {format}",
    settings_daily_template_label: "📝 القالب: {template}",
    settings_source_label: "مصدر الإعدادات",
    settings_source_desc: "تلقائي = يكتشف إعدادات Daily Notes / Periodic Notes. يدوي = استخدم الحقول أدناه.",
    settings_daily_folder: "مجلد الملاحظات اليومية",
    settings_daily_folder_desc: "المسار النسبي للمجلد (اتركه فارغاً للجذر)",

    // GridRenderer strings
    grid_expand_children: "عرض العادات الفرعية",
    grid_collapse_children: "إخفاء العادات الفرعية",
    grid_diary_label: " يومياتي",
    grid_diary_exists_tooltip: "تم تسجيل يومية لهذا اليوم",
    grid_diary_add_tooltip: "تدوين ملاحظة اليوم",
    grid_hint_tip: "💡 تلميح: اضغط مطولاً أو بالزر الأيمن على أي مربع لتسجيل ملاحظة صوتية على العادة.",
    grid_hint_hide: "إخفاء التلميح",
    grid_no_note_tooltip: "📝 لا توجد ملاحظة لهذا اليوم",
    grid_click_open_note_tooltip: "اضغط لفتح الملاحظة",
    grid_type_break: "كسر عادة",
    grid_type_build: "بناء عادة",
    grid_collapse_expand_tooltip: "إخفاء / عرض العادات الفرعية",
    grid_open_habit_page_tooltip: "فتح صفحة العادة",
    grid_no_linked_page_notice: "⚠️ لا توجد صفحة مرتبطة",
    grid_cell_right_click_hint: "كليك يمين لإضافة تعليق",
    grid_habit_archived_tooltip: "🔒 تم إيقاف/أرشفة هذه العادة\n{title}",
    grid_create_note_confirm: "لا توجد ملاحظة لهذا اليوم. هل تريد إنشاؤها؟",
    grid_btn_create: "إنشاء",
    grid_create_note_error: "⚠️ تعذر إنشاء الملاحظة",
    grid_no_note_error: "⚠️ لا توجد ملاحظة لهذا اليوم",
    grid_habit_not_found_error: "⚠️ العادة غير موجودة في الملاحظة",
    grid_update_habit_error: "⚠️ حدث خطأ أثناء تحديث العادة",
    grid_completion_rate: "معدل الإنجاز",
    grid_completion_gap: "🚀 انطلاقة جيدة! باقي {gap}% لتعادل إنجاز الأسبوع الماضي ({lastRate}%).",
    grid_completion_match: "🔥 ممتاز! لقد عادلت رقمك السابق ({lastRate}%). خطوة واحدة لكسر الحاجز!",
    grid_completion_break: "🏆 بطل! تم كسر الحاجز، أنت تتفوق بـ (+{lead}%) عن الأسبوع الماضي.",
    completion_msg_1: "🌟 أحسنت! أنجزت كل عادات اليوم",
    completion_msg_2: "💪 يوم مثالي!",
    completion_msg_3: "🎯 ممتاز! واصل هكذا",
    habit_log_disabled: "ميزة سجل المتابعة معطلة من الإعدادات.",
    save_habit_first_for_comments: "احفظ العادة أولاً لتتمكن من إضافة وقراءة التعليقات.",
    tab_basics_num: "1. الأساسيات",
    tab_gradation_num: "2. التدرج",
    tab_log_num: "3. السجل",
    habit_name_placeholder: "مثال: صلاة الفجر في المسجد",
    rename_old_notes_label: "إعادة التسمية في جميع الملاحظات القديمة؟ (اختياري)",
    rename_old_notes_hint: "💡 سيتم استبدال الاسم الحالي وكل الأسماء السابقة لهذه العادة بالاسم الجديد في كل ملفاتك.",
    no_linked_file: "📁 لا يوجد ملف مرتبط (سيُنشأ تلقائياً)",
    child_habits_label: "العادات المرتبطة بها:",
    color: "اللون",
    schedule_days: "أيام التكرار",
    sun_short: "الأحد", mon_short: "الاثنين", tue_short: "الثلاثاء", wed_short: "الأربعاء", thu_short: "الخميس", fri_short: "الجمعة", sat_short: "السبت",
    habit_engineering_summary: "💡 هندسة العادات (خياري): أسئلة للتحليل العميق",
    habit_type_build: "بناء عادة",
    habit_type_break: "كسر عادة",
    notes_label: "ملاحظات (اختياري)",
    notes_hint: "مساحة حرة: الوقت، المكان، تذكير، أي شيء تريده",
    notes_placeholder: "مثال: هذه العادة أعملها الساعة 6 صباحاً بعد القهوة...",
    identity_label: "الهوية المستهدفة",
    identity_hint_build: "من تريد أن تصبح؟ بدل \"أريد قراءة كتاب\" قل \"أنا قارئ نهم\"",
    identity_hint_break: "من تريد أن تصبح؟ (مثال: \"أنا شخص يتحكم برغباته\")",
    identity_placeholder_build: "مثال: أنا قارئ منتظم",
    identity_placeholder_break: "مثال: أنا شخص غير مدخن",
    cue_label_build: "الإشارة (متى وأين؟)",
    cue_label_break: "الإشارة (إخفاء/إزالة)",
    cue_hint_build: "سوف أقوم بـ [العادة] في الساعة [...] في مكان [...]",
    cue_hint_break: "ما الذي يدفعك للعادة السيئة؟ ألغِ المحفز أو أخفِه",
    cue_placeholder_build: "مثال: بعد صلاة الفجر مباشرة في غرفة المكتب",
    cue_placeholder_break: "مثال: حذف التطبيق المشتت",
    friction_label_build: "السهولة (تسهيل البدء)",
    friction_label_break: "التصعيب (زيادة العقبات)",
    friction_hint_build: "ابدأ بأقل من دقيقتين — مثال: لبس الحذاء الرياضي فقط",
    friction_hint_break: "كيف تزيد العقبات؟ أضف خطوات تمنعك من البدء",
    friction_placeholder_build: "مثال: تجهيز ملابس الرياضة من الليل",
    friction_placeholder_break: "مثال: إبعاد الهاتف عن غرفة النوم",
    reward_label_build: "المكافأة (فورية)",
    reward_label_break: "العقوبة (فورية)",
    reward_hint_build: "كافئ نفسك فوراً — مثال: قهوة، شوكولاتة صغيرة، شربة ماء بارد",
    reward_hint_break: "ما العقوبة الفورية إذا استسلمت؟",
    reward_placeholder_build: "مثال: كوب قهوة مفضل",
    reward_placeholder_break: "مثال: التبرع بـ 50 ريال كعقوبة",
    gradation_hint: "تدرج في عملك حتى تصل لغايتك",
    gradation_explanation: "💡 فكرة التدرج: العادات الكبرى تبدأ بخطوات صغيرة جداً. ركز فقط على المرحلة الحالية وتلبية 'شرط الانتقال'. الاستمرارية تسبق الكمية.",
    target_habit_level_label: "مستوى العادة المستهدف",
    condition_label: "شرط الانتقال",
    cond_select: "اختر الشرط...",
    cond_7d: "7 أيام متواصلة",
    cond_14d: "14 يوماً متواصلة",
    cond_21d: "21 يوماً متواصلة",
    cond_30d: "30 يوماً متواصلة",
    cond_lifestyle: "بدون شرط (أسلوب حياة)",
    placeholder_lvl_1: "أقل القليل: آية واحدة، أو عدة ضغط واحدة",
    placeholder_lvl_2: "البداية الفعلية: صفحة، أو 5 دقائق رياضة",
    placeholder_lvl_3: "الزيادة المعتدلة: صفحتين/ربع حزب، أو 15 دقيقة رياضة",
    placeholder_lvl_4: "مستوى التحدي: 10 صفحات/نصف جزء، أو 30 دقيقة رياضة",
    placeholder_lvl_5: "الغاية المنشودة: جزء يومياً، أو 45 دقيقة رياضة",
    error_fill_level: "املأ الهدف والشرط أولاً",
    save_btn: "💾 حفظ",
    color_rose: "وردي", color_pink: "زهري", color_orange: "برتقالي", color_amber: "ذهبي", color_lime: "ليموني", color_green: "أخضر", color_teal: "أخضر مائي", color_cyan: "سماوي", color_blue: "أزرق", color_indigo: "نيلي", color_purple: "بنفسجي", color_slate: "رمادي",
    yes_sure: "نعم، متأكد",
    settings_source_daily: "متصل بـ Daily Notes (تلقائي)",
    settings_source_periodic: "متصل بـ Periodic Notes (تلقائي)",
    settings_source_manual: "إعدادات يدوية",
    settings_source_defaults: "قيم افتراضية (YYYY-MM-DD)",
    settings_source_manual_opt: "يدوي",
    settings_daily_format: "صيغة التاريخ",
    settings_daily_format_desc: "صيغة Moment.js لاسم الملف",
    settings_habit_context_heading: "💬 سياق العادات (التعليقات)",
    settings_journal_heading: "📝 يومياتي",
    settings_collapse_expand_tooltip: "إخفاء / عرض الفروع",
    schedule_daily: "🔁 يومي",
    schedule_days_count: "🗓️ {count} أيام",
    action_move_up: "نقل لأعلى",
    action_moved_up_success: "✅ تم النقل لأعلى",
    action_move_down: "نقل لأسفل",
    action_moved_down_success: "✅ تم النقل لأسفل",
    action_delete_confirm: "⚠️ حذف \"{name}\"؟",
    action_archive: "أرشفة",
    action_archived_success: "✅ تم الأرشفة",
    settings_expand_children: "عرض الفروع",
    settings_collapse_children: "إخفاء الفروع",
    settings_no_archived_habits: "لا توجد عادات مؤرشفة",
    settings_archive_date: "تاريخ الأرشفة",
    settings_longest_streak: "أطول سلسلة",
    action_restore: "استعادة",
    action_restored_success: "✅ تم الاستعادة",
    action_delete_permanently: "حذف نهائي",
    action_delete_permanently_confirm: "⚠️ حذف \"{name}\" نهائياً؟",
    action_deleted_permanently_success: "✅ تم الحذف النهائي",
    notice_deleted_habit: "🗑️ تم حذف \"{name}\"",
    action_undo: "تراجع",
    action_restored_habit_success: "✅ تم استعادة العادة",

    // StreakStatsComponent
    stats_days_one: "يوم",
    stats_days_two: "يومين",
    stats_days_few: "أيام",
    stats_days_many: "يوماً",
    stats_days_other: "يوم",
    stats_none: "لا يوجد",
    stats_calculating: "جاري الحساب...",
    stats_longest_label: "أطول سلسلة:",
    stats_current_label: "السلسلة الحالية:",
    stats_first_completion: "أول إنجاز",
    stats_days_ago: "(مضى {count} {unit})",
    stats_consistency: "الالتزام",
    stats_last_30_days: "(آخر 30 يوماً)",
    stats_recovery_speed: "سرعة التعافي",
    stats_recovery_tooltip: "كلما قل هذا الرقم، كلما كنت أسرع في العودة بعد الانقطاع",
    stats_recovery_avg: "تعود للعادة خلال {days} يوم في المتوسط",
    stats_recovery_behind: "متأخر عن المعتاد ({days}يوم).. بسّط وعد اليوم!",
    stats_recovery_resilience: "مرونة عالية - بطل التعافي!",
    stats_recovery_good: "تعافي جيد غالباً",
    stats_recovery_simplify: "قرار: بسّط العادة فور السقوط",
    stats_leak_alert: "تنبيه تسريب",
    stats_leak_days: "{count} أيام",
    stats_leak_simplify: "(بسّط العادة لإيقاف النزيف!)",
    stats_error_loading: "خطأ في جلب الإحصائيات",

    // LogViewer
    log_header_title: "سجل المتابعة والتعليقات",
    log_add_note_btn: "🎙️ أضف ملاحظة لليوم",
    log_loading: "جاري تحميل السجل...",
    log_empty_state: "السجل فارغ. استمر في العادة ووثق تقدمك يوماً بيوم!",
    log_error: "خطأ في تحميل السجل",
    date_format_log_day: "DD MMMM",

    // DiaryRenderer
    diary_weekly_title: "يوميات الأسبوع",
    diary_add_today_btn: "تدوينة اليوم",
    diary_mode_grouped: "حسب الأيام",
    diary_mode_timeline: "خط زمني",
    diary_mode_by_type: "حسب النوع",
    diary_empty_title: "لا توجد تدوينات في هذا الأسبوع",
    diary_empty_desc: "اكتب تدوينة اليوم من الزر بالأعلى. سيتم حفظها داخل ملف اليوم نفسه.",
    diary_count_one: "تدوينة",
    diary_count_two: "تدوينتان",
    diary_count_few: "{count} تدوينات",
    diary_count_many: "{count} تدوينة",
    diary_count_other: "{count} تدوينة",
    diary_add_entry_tooltip: "إضافة تدوينة لهذا اليوم",
    date_format_diary_header: "dddd، D MMMM",

    // DashboardRenderer
    stats_calculating_lifetime: "جاري الحساب التراكمي...",
    stats_calculating_lifetime_progress: "جاري الحساب التراكمي... ({progress}/{total} ملف) ⏳",
    stats_lifetime_achievements: "إجمالي الإنجازات",
    stats_lifetime_subtitle: "🌟 علامة [x] مسطّرة في تاريخك",
    stats_calculate_btn: "بدء الحساب",
    stats_identity_mix: "توزيع الهوية",
    stats_identity_build: "بناء: {count}",
    stats_identity_break: "ترك: {count}",
    stats_advisory_tip: "نصيحة: إذا اتخذت قراراً جديداً بناءً على هذه الأرقام، اكتبه فوراً في ملاحظة اليوم أو في ملف العادة لتثبيته.",
    stats_weekly_trends_title: "📈 اتجاهات الأسابيع الأخيرة",
    stats_weekly_trends_desc: "نظرة على آخر 4 أسابيع فقط (وليس كل تاريخك) لمعرفة مسارك الحالي واتخاذ قرارات تصحيحية فورية.",
    stats_table_header_week: "الأسبوع",
    stats_table_header_rate: "نسبة الإنجاز",
    stats_table_header_trend: "التغير (Trend)",
    stats_week_current: "هذا الأسبوع (مختار)",
    stats_week_last: "الأسبوع الماضي",
    stats_week_index: "الأسبوع -{index}",
    stats_trend_up: "🟢 تقدم بـ {diff}%",
    stats_trend_down: "🔴 تراجع بـ {diff}%",
    stats_trend_stable: "➖ استقرار",
    stats_focus_best_label: "العادة الأقوى التزاماً",
    stats_focus_worst_label: "العادة الأضعف (نقطة تسريب)",
    stats_daily_patterns_title: "📅 تحليل الأنماط اليومية (المتوسط)",
    stats_daily_patterns_desc: "متوسط أداء كل يوم خلال الـ 28 يوماً الماضية. اكتشف يوم 'التسريب' وعالجه، ويوم ذروتك واستغله.",
    stats_daily_patterns_guideline: "توجيه: أضعف أيامك باللون الأحمر، وهو 'نقطة التسريب'. أما أقوى أيامك بالأخضر، فحاول استنساخ ما تفعله فيه!",
    success_updated: "✅ تم تحديث {name}",
    error_habit_file_not_found: "⚠️ لم يتم العثور على ملف العادة.",
    comma_separator: "، ",
    error_file_exists: "يوجد ملف بالفعل في المسار المستهدف: \"{path}\"",
    error_duplicate_habit_name: "توجد عادة نشطة أو مؤرشفة بنفس الاسم بالفعل: \"{name}\"",
    rename_confirm_title: "⚠️ تحديث جميع الملفات",
    rename_confirm_desc: "سيتم تغيير \"{oldName}\" إلى \"{newName}\" في {count} ملف.",
    rename_confirm_btn_all: "نعم، تحديث الكل",
    rename_cancelled_notice: "⚠️ تم الإلغاء. المحدث: {count}",
    rename_success_notice: "✅ تم تنظيف {count} رابط تاريخي بنجاح",
    rename_error_notice: "❌ خطأ أثناء التحديث",
    rename_no_files_notice: "لم يتم العثور على ملفات قديمة للتحديث",
    habit_notes_free_space_marker: "> **مساحة حرة للتدوين:**",
    habit_notes_placeholder: "> (اكتب هنا دوافعك العميقة أو أفكارك عن بناء هذه العادة...)",
    habit_template_engineering_title: "> [!info] 🧠 هندسة العادة",
    habit_template_identity_prefix: "> **الهوية التي أريدها:**",
    habit_template_cue_prefix: "> **المحفز (الوقت/المكان):**",
    habit_template_friction_prefix: "> **تقليل الاحتكاك:**",
    habit_template_reward_prefix: "> **المكافأة:**",
    habit_template_append_marker_comment: "<!-- تُضاف التدوينات والملاحظات الصوتية تلقائياً أدناه بواسطة الإضافة -->",
    error_modifying_note: "⚠️ حدث خطأ أثناء تعديل الملاحظة.",
  },
};

